
##################################################################BABY###################################################################

# embedding_size: 64
# n_ui_layers: 4
# n_layers: 1

# learning_rate_scheduler: [0.96, 50]
# lambda_coeff: 0.9
# reg_weight: 1e-4
# learning_rate: 0.001

# cl_loss: 0.01
# temperature: [0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 0.1] # 0.2
# image_knn_k: 40
# text_knn_k: 15

# dropout_rate : 0.1

# hyper_parameters: ["temperature"]

#####################################################################Sports################################################################
embedding_size: 64
n_ui_layers: 3
n_layers: 1

learning_rate_scheduler: [0.96, 50]
lambda_coeff: 0.9
reg_weight: 1e-4
learning_rate: 0.001

cl_loss: 0.03
temperature: [ 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9,0.1] # 0.2
image_knn_k: 10
text_knn_k:  10

dropout_rate : 0.1

hyper_parameters: ["temperature"]


#####################################################################################################################################